#!/bin/sh
#
if [ "$#" -ne 1 ]; then 
    echo "Usage: enter one argument that is a file/directory" 
    exit 1
fi

echo "file $1"
[ ! -e "$1" ] && echo " does not exist" && exit 1
[ -r "$1" ] && echo " is readable"
[ -w "$1" ] && echo " is writable"
[ -x "$1" ] && echo " is executable"
exit 0
